kafka:
  bootstrap.servers: "localhost:9092,localhost:9093,localhost:9094"
  #bootstrap.servers: "sb-uka7:9092,sb-uka8:9092,sb-uka9:9092"
  topicSource: "sb-all"
  topicSink: "sb-solr"
  auto.offset.reset: "earliest"
  #group.id: "docproc"


simpleValues:
  SKIPRECORDS : "false"
  zwei: "drei"

xsltTemplates:
  simpleValues:

    XSLTTEMPLATESKIP : "belongs.2.orange.repository.xsl"
    TRANSFORMERIMPL: "net.sf.saxon.TransformerFactoryImpl"

  XSLT_PIPE:
    0: "weedholdings.xsl"
    1: "swissbib.solr.step1.xsl"
    2: "vufind.special.green.xsl"
    3: "swissbib.solr.vufind2.xsl"

  startTemplate:
    holdingsStructure: "collect.holdings.xsl"


XSLT_PIPE:
  0:
    "name" : "weedholdings.xsl"
  1:
    "name": "swissbib.solr.step1.xsl"
  2:
    "name": "vufind.special.green.xsl"
  3:
    "name": "swissbib.solr.vufind2.xsl"



plugins:

  PLUGINS_TO_LOAD:
    0: "org.swissbib.documentprocessing.plugins.FulltextContentEnrichment"
    1: "org.swissbib.documentprocessing.plugins.RemoveDuplicates"
    2: "org.swissbib.documentprocessing.plugins.GNDContentEnrichment"
    3: "org.swissbib.documentprocessing.plugins.DSV11ContentEnrichment"
    4: "org.swissbib.documentprocessing.plugins.CreateSecondISBN"
    5: "org.swissbib.documentprocessing.plugins.DeleteWeededDocuments"
    6: "org.swissbib.documentprocessing.plugins.SolrStringTypePreprocessor"
    7: "org.swissbib.documentprocessing.plugins.CreateLibraryFacets"

  "PLUGINS_IN_PRODUCTIONMODE":
    1: "org.swissbib.documentprocessing.plugins.RemoveDuplicates"
    2: "org.swissbib.documentprocessing.plugins.CreateSecondISBN"
    3: "org.swissbib.documentprocessing.plugins.CreateLibraryFacets"
    4: "org.swissbib.documentprocessing.plugins.SolrStringTypePreprocessor"
    5: "org.swissbib.documentprocessing.plugins.FulltextContentEnrichment"
    6: "org.swissbib.documentprocessing.plugins.GNDContentEnrichment"

  FulltextContentEnrichment:
    ALLOWED_DOCUMENTS: 'http://www\.ub\.unibas\.ch/tox/IDSLUZ/.*?/PDF###http://www\.ub\.unibas\.ch/tox/IDSBB/.*?/PDF###http://www\.ub\.unibas\.ch/tox/HBZ/.*?/OCR###http://d-nb\.info/.*?/04###http://aleph\.unisg\.ch/hsgscan/.*?\.pdf###http://opac\.nebis\.ch/objects/pdf/.*?\.pdf###http://biblio\.unizh\.ch/objects/pdf/.*?\.pdf###http://libraries\.admin\.ch/gw/toc/pdf/.*?\.pdf###https://www.edubs.ch/unterstuetzung/buecher/.*?\.pdf###https://www.edubs.ch/unterstuetzung/bibliothek/.*?\.pdf'
    HTTP_FETCH_NOT_ALLOWED: 'http://opac\.nebis\.ch/objects/pdf/.*?\.pdf###http://opac.nebis.ch/objects/pdf03/.*?\.pdf'
    REMOTEFETCHING: true
    ALLOWED_CONTENTTYPE: 'application/pdf###application/pdf;charset=UTF-8###application/pdf;charset=Binary'
    MAXLENGTH_FETCHED_DOCUMENTS: '30000'
    JDBCDRIVER: 'org.mariadb.jdbc.Driver'
    JDBCCONNECTION: 'jdbc:mysql://localhost:3306/remotecontent'
    #JDBCCONNECTION: 'jdbc:mysql://xxxx:3306/remotecontent'
    #user: 'xxx'
    #passwd: 'xxx'
    user: 'bla'
    passwd: 'bla'


  GNDContentEnrichment:
    ID_PATTERN_TO_REPLACE: '?##?'
    PATTERN_FOR_ID: '^(\\(.*?\\))(.*)$'
    TAGS_TO_USE: '400_a###400_b###400_c###400_d###400_x###410_a###410_b###411_a###411_b###430_a###450_a###450_x###451_a###451_x'
    TAGS_TO_USE_FOR_MACS: '750_a'
    DB_HOST: 'localhost'
    #DB_HOST: 'sb-xxx.swissbib.unibas.ch'
    DB_PORT: '29017'
    #AUTHENTICATION_DB: 'xxx'
    #AUTHENTICATION_USER: ''
    #AUTHENTICATION_PASSWD: 'xxxx'

    CONTENT_DB: 'nativeSources'
    CONTENT_COLLECTION: 'sourceDNBGND1'
    SEARCH_FIELD: 'gndid'
    RESPONSE_FIELD: 'gndfields'
    RESPONSE_FIELD_MACS: 'macsfields'

  SolrStringTypePreprocessor:
    #NAV_FIELD_FORM_SYNONYMS_DIR: '/swissbib_index/solrDocumentProcessing/MarcToSolr/dist/predoc'
    NAV_FIELD_FORM_SYNONYMS_FILE: 'formsynonyms.txt'



  CreateLibraryFacets:
    LIBADMIN_DEFINITIONS: 'plugins/library-facet-green.json'



fileBasedConfig:
  SOLRDOCSIZE : 1000
  BASENAME_FILE_SOLRDOCS : "solrout.xml"
  INTERMEDIATE_RESULT_OUTPUT_DIR_FILE: